# Generated by Django 4.1.6 on 2023-02-07 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
