# Generated by Django 4.1.6 on 2023-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendingMachine", "0002_item_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
