# Generated by Django 4.1.6 on 2023-02-07 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("vendingMachine", "0011_alter_item_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
