# Generated by Django 4.1.6 on 2023-02-07 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0012_alter_item_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendingMachine.vendingmachine')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='time_stamp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendingMachine.time'),
        ),
    ]
