# Generated by Django 4.1.6 on 2023-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0014_remove_item_time_stamp_time_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='items',
        ),
        migrations.AddField(
            model_name='time',
            name='items',
            field=models.JSONField(null=True),
        ),
    ]
